### PR TITLE
Support for transparency and more function types

### PR DESCRIPTION
**Pull request by thielema**
This branch is now almost half a year old and I found it useful as it is. However, it contains breaking changes with respect to shading and adding more features may break again. I increased version to 1.7. The new functionality is demonstrated in `Test/test.hs`.

### CODE REVIEW

**Comment by hsyl20** [comment]
Awesome!

Would you like to become the new maintainer of HPDF? You know much more than I do about the internals. I can transfer you the github repo if you want.

**Comment by thielema** [comment]
@hsyl20 
Thank you for your offer, but I think if I would invest more time in `HPDF` I would rather fork or rewrite the code, e.g. to using module qualification.

**Comment by hsyl20** [comment]
It would be fine by me. I didn't write any of the code and I don't use `HPDF` in any of my projects. You could make `HPDF` 2.0 a major rewrite.

**Comment by thielema** [comment]
On Thu, 22 Feb 2024, Sylvain Henry wrote:

> It would be fine by me. I didn't write any of the code and I don't use 
> HPDF in any of my projects. You could make HPDF 2.0 a major rewrite.

I have no actual plans for such a rewrite. You may make me a 
co-maintainer, though. I have used HPDF in three projects, though the last 
one has become obsolete:
   https://hackage.haskell.org/package/boomwhacker
   https://hackage.haskell.org/package/med-module
   https://hackage.haskell.org/package/internetmarke

**Comment by hsyl20** [comment]
Ok, I've added you as a collaborator to this repository and as a co-maintainer on Hackage. Cheers!

**Pull request merged**
